#!/bin/bash
set -ETeu -o pipefail

printHelp() {
	echo "usage: ${0} <name> <workspace>"
	exit 1
}

if [[ "${1}" == "" || "${2}" == "" ]]; then
	printHelp
fi

name="${1}"
buildroot="${2}"

build_number=$(git rev-list HEAD | wc -l)

rpmbuild --verbose \
		 -ba ${buildroot}/libvmod-maxmind-geoip.spec \
		 --define "_version_number 4.1.0" \
		 --define "_build_number ${build_number}" \
		 --define "_source ${buildroot}"

echo "rpmbuild complete"

for e in $(find ~/rpmbuild -name ${name}*.rpm); do
	echo "sign and publish $e"
	/usr/bin/sign-rpm $e
	/usr/bin/publish-rpm $e
	if [[ ! "${e}" =~ (debuginfo|src.rpm) ]]; then
		rpm=$(echo ${e}|sed 's|.*/||')
	fi
	rm -f $e
done

echo "done with rpms. Build properties file"
echo "BUILD=${buildnumber}" > ${buildroot}/version.properties
echo "VERSION=${version}-${buildnumber}" >> ${buildroot}/version.properties
echo "RPM=$rpmfile" >> ${buildroot}/version.properties
echo $rpm
exit 0
