/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "vmod_geo.h"
#include <maxminddb.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_OpenMMDB(void);
extern void test_BadIP(void);
extern void test_CaliforniaIP(void);
extern void test_ParisFranceIP(void);
extern void test_LookupCity(void);
extern void test_LookupState(void);
extern void test_LookupCountry(void);


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  UnityBegin();
  Unity.TestFile = "tests.c";
  RUN_TEST(test_OpenMMDB, 15);
  RUN_TEST(test_BadIP, 22);
  RUN_TEST(test_CaliforniaIP, 31);
  RUN_TEST(test_ParisFranceIP, 40);
  RUN_TEST(test_LookupCity, 48);
  RUN_TEST(test_LookupState, 57);
  RUN_TEST(test_LookupCountry, 66);

  return (UnityEnd());
}
